### PR TITLE
Add Rolling Update and Readiness Check

### PR DESCRIPTION
**Pull request by Kevcpro**

### CODE REVIEW

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
In the yaml files, the added probes should not have the `tag` and `end` comments

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
Because health checks are new files, set license year to `2022` only

**Review by gkwan-ibm — COMMENTED** [review]
The readme does not mention the health checks. Remove the tag and end comments from the  health check java files

**Review by gkwan-ibm — COMMENTED** [review]
I asked to remove the tag and end comments from the added probes , not all tag and end from the finish/kubernetes.yaml. It will screw up the hotspots.

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
Fix the spacing for he health check java files

**Review by gkwan-ibm — CHANGES_REQUESTED** [review]
@t27gupta 
in finish/kubernetes.yaml. some tags still were removed. Would you restore them and make sure all hotspots work by turnip1?

**Review by priyyanshi — APPROVED** [review]

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
