### PR TITLE
Change environment variable name

### PR DESCRIPTION
**Pull request by andrewdes**
The guide in its current state is broken since the `PASSWORD` environment variable is getting overridden. So, when we use MPConfig to inject a value from the `PASSWORD` environment variable, it is not the correct value that we are obtaining. By changing the environment variable name to something less generic such as `PING_PASSWORD`, we can ensure we obtain the correct value.

### CODE REVIEW

**Comment by evelinec** [comment]
This PR is a workaround to address issue found in #47, so that the guide is not broken. @andrewdes will continue to investigate the relevant root cause of this problem. @yeekangc any opinions on this?

**Comment by andrewdes** [comment]
I have found what is causing the override of the `PASSWORD` environment variable: https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/helpers/runtime/docker-server.sh

**Comment by evelinec** [comment]
Checked with @gkwan-ibm, he's good with this fix too.

**Comment by yeekangc** [comment]
Qualifying these are fine.  End users should be free to use what they want.  Really, what is done by the Docker image needs to be fixed.  Please file an issue ASAP if not add a comment to an existing issue.

**Pull request merged**
