### PR TITLE
Automation: Update Feature Versions

### PR DESCRIPTION
**Pull request by GuidesBot**
**Updated**
finish/inventory/src/main/liberty/config/server.xml
finish/system/src/main/liberty/config/server.xml
start/inventory/src/main/liberty/config/server.xml
start/system/src/main/liberty/config/server.xml

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
@k-rtik 
- [ ] update the index.html
  -  ` <h2>MicroProfile</h2>` to   ` <h2>Eclipse MicroProfile</h2>`

**Comment by gkwan-ibm** [comment]
@k-rtik 
- [ ] Would you update the pom.xml with following?
```
    <!--  Provided dependencies-->
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>8.0.0</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.eclipse.microprofile</groupId>
      <artifactId>microprofile</artifactId>
      <version>3.3</version>
      <type>pom</type>
      <scope>provided</scope>
    </dependency>
```

**Comment by gkwan-ibm** [comment]
@k-rtik 
- [ ] is  start/system/src/main/webapp/index.html missing appSecurity-3.0.html

**Comment by DannyS03** [comment]
- tested/verifed on **qa**.

**Pull request merged**
